version: '3.1'

services:
  app:
    image: mokhlesur96/dj:9ca75ce64a62b7f11929ab24747a47a95d154433
    container_name: py-depl
#    build:
#      context: .
    ports:
      - 8000:8000
    restart: always
    networks:
      - py-app
      - py-db


networks:
  py-app:
    external: true

