version: '3.1'

services:

  database:
    image: postgres
    container_name: go-api-db-svc
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    volumes:
      - ${PWD}/database/data/:/var/lib/postgresql/data/

