{{- if .Values.celerFlower.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-celery-flower
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "django-helm.labels" . | nindent 6 }}
      app.kubernetes.io/component: celery-flower
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "django-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: celery-flower
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/django-core/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.celeryBeat.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.celeryBeat.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.celerFlower.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-config
          env:
            - name: aliyun_logs_{{.Release.Name}}-celery-flower
              value: stdout
          ports:
            - name: flower
              containerPort: {{ .Values.celerFlower.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.celerFlower.resources | nindent 12 }}
      {{- with .Values.celerFlower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celerFlower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celerFlower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end -}}