apiVersion: v1
kind: PersistentVolume
metadata:
  name: py-db-pv

spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/k8s/kub
    type: DirectoryOrCreate