apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: py-db-sts

spec:
  serviceName: py-server-svc
  replicas: 1

  selector:
    matchLabels:
      app: psql

  template:
    metadata:
      labels:
        app: psql

    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: py-db-secret
            - configMapRef:
                name: py-db-cm

          ports:
            - containerPort: 5432
              name: postgresql

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: psql-storage

      volumes:
        - name: psql-storage
          persistentVolumeClaim:
            claimName: py-db-pvc


