{{- if .Values.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: 5Gi
  {{- end -}}