apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-django-server
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: django-server
spec:
  replicas: {{ .Values.djangoServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "django-helm.labels" . | nindent 6 }}
      app.kubernetes.io/component: django-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "django-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: django-server
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/django-core/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.djangoServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.djangoServer.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /
              port: django
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: django
            failureThreshold: 1
            periodSeconds: 10
          {{- with .Values.djangoServer.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-config
          env:
            - name: aliyun_logs_{{.Release.Name}}-django-server
              value: stdout
          ports:
            - name: django
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.djangoServer.resources | nindent 12 }}
      {{- with .Values.djangoServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.djangoServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.djangoServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}