{{- if .Values.migrateJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-migrate
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate-job
spec:
  template:
    #    ttlSecondsAfterFinished: 60
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.djangoServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.djangoServer.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python",  "manage.py", "migrate", "--settings=$(DJANGO_SETTINGS_MODULE)"]
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-config
      restartPolicy: Never
  backoffLimit: 0
  {{- end -}}