name: dj-ci

on:
  push:
    branches:
      master

jobs:
  push-to-dockerhub:
    name: Push Python Image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Code
        uses: actions/checkout@v3

      - name: Build and Push Python Image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_KEY }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dj:$GITHUB_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dj:$GITHUB_SHA
            
