{{- if .Values.grpcServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-grpc-server
  labels:
    {{- include "django-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grpcServer.service.type }}
  ports:
    - port: {{ .Values.grpcServer.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "django-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc-server
  {{- end -}}